# Curso Deep Learning - Exercício pré-curso Python - NumPy

Este é um notebook Jupyter contendo exercícios de programação matricial utilizando o Python e biblioteca NumPy.
Estes exercícios servem para familiarizar o participante na linguagem Python para manipulação matricial.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o Python, consultar documentação e tutoriais disponíveis na Internet.

Estes exercícios são de dificuldade **intermediária para difícil**, usaremos programação
avançada Python, explorando listas, dicionários, programação matricial e programação
orientada a objeto.

### Python

O curso será feito utilizando a versão Python 3.6, assim recomenda-se que estes exercícios sejam feitos com o Python 3.
Recomenda-se instalar o Jupyter e o Python utilizando-se o [Anaconda](https://www.continuum.io/downloads) - uma distribuição
focada em Data Science, contendo os principais pacotes usados nesta área.

### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python. Se você precisar de ajuda sobre como usar os Notebooks Jupyter, veja [beginner-guide](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/).

Instale o Jupyter nbextensions que é um conjunto de ferramentas auxiliares. Habilite o "Table of Contents" do nbextensions para que este notebook fique itemizado.

Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

# Exercícios básicos

Vamos começar! Comece imprimindo seu nome e e-mail aqui:

In [1]:
# preencha com seus dados
print('My name is Gabriel Moraes Barros')
print('My email is gabrielmoraesbarros@gmail.com')

My name is Gabriel Moraes Barros
My email is gabrielmoraesbarros@gmail.com


## Listas

Seguem alguns exercícios com lista. Python é muito bom para processar listas. Uma lista é uma sequência de elementos 
separados por vírgula dentro de chaves:

In [3]:
mylist = [5, 8, 'abc', 0, 8.3]

### Imprimindo o número de elementos de uma `mylist` e alguns de seus elementos

In [4]:
print(len(mylist))
print(mylist[0])
print(mylist[-1])  # observe o índice -1 (o que isso significa?)

5
5
8.3


índice [-1] significa último elemento da lista 

## Seja uma lista de 10 elementos numéricos sequenciais, começando em zero

O código a seguir é típico para criar uma lista com os 10 primeiros inteiros maiores ou iguais a zero: inicializa-se lista vazia, para cada i entre 0 e menor que 10, faz append na lista a:

In [5]:
a = []
for i in range(10):
    a.append(i)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## List Comprehension

Esta mesma lista pode ser criada utilizando a construção denominada "List Comprehension" ou
"Compreensão de Lista" em portugues. Coloque este termo no Google adicionando python na frente na forma:
"python comprehension list" e você poderá ver vários exemplos e tutoriais sobre o assunto. É uma forma compacta que fazer um append iterativo numa lista:

Veja como o trecho acima foi reduzido para uma linha apenas:

In [7]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
m_list = ['r', 'i', 'c', 'a', 'r', 'd', 'o']
new_list = []
for k,i in enumerate(m_list):
    new_list.append(str(k)+i)
print(new_list)

['0r', '1i', '2c', '3a', '4r', '5d', '6o']


- Explique o que o enumerate faz no programa acima:

<b> Resposta: </b> O enumerate serve para iterar sobre o "m_list". k sendo o iterador e i sendo o elemento "k" da lista "m_list".

- Repita o mesmo exercício de criar a lista new_list, porém utilizando list comprehension:
   

In [16]:
m_list = ['r', 'i', 'c', 'a', 'r', 'd', 'o']
n_list = [str(k)+i for k,i in enumerate(m_list)] # utilize aqui o list comprehension

In [17]:
print(n_list)

['0r', '1i', '2c', '3a', '4r', '5d', '6o']


## Fatiamento em Python

Um conceito fundamental em Python é o do fatiamento "slicing", em inglês. É um conceito que será muito usado
durante todo o curso. Estude bem isso. Inicialmente iremos trabalhar com fatiamento de lista, mas posteriormente
com arrays (ou tensores) utilizando o NumPy

In [8]:
print(a[3:5])

[3, 4]


### Criar e imprimir uma lista a partir da lista "a" já criada, porém apenas alguns elementos

In [32]:
# imprima os elementos ímpares de a
print(a[1::2])
# imprima os elementos pares de a
print(a[::2])
# imprima os últimos 3 elementos da lista (utilize índice negativo, pesquise na Internet)
print(a[-3:])
# Imprima os 3 primeiros elementos da lista (veja quando é possível ignorar valores iniciais e finais)
print(a[:3])
print(a[1:4])

[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8]
[7, 8, 9]
[0, 1, 2]
[1, 2, 3]


<b>Não entendi</b>: (veja quando é possível ignorar valores iniciais e finais).

In [33]:
# Veja o significado do passo:
print(a[::2])
print(a[::-1])

[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [39]:
# imprima os elementos ímpares na order reversa, do maior para o menor
print(a[1::2][::-1])

[9, 7, 5, 3, 1]


## Tuplas

In [40]:
b = tuple(a)
print(b)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


A principal diferença entre uma lista e uma tupla é:

A tupla é uma estrutura de dados heterogênea, imutável e com estrutura. É interessante ser usada, por exemplo, (nome,cpf) já que a pessoa não vai trocar de CPF. Tuplas podem ser usadas como chaves em dicionários. Geralmente a tupla é uma sequência de coisas distintas, mas útil para lidar com estes itens ao mesmo tempo.


A lista é uma estrutura homogênea e mutável. Geralmente é uma sequência de items da mesma natureza, e você lida com eles individualmente


# Dicionários em Python

Python possui uma estrutura de dados muito versátil denominada dicionário.

In [42]:
rob_record = {'nome': 'Roberto', 'idade': 18}
print(rob_record['nome'])

Roberto


In [43]:
rob_record['idade'] = 20
print(rob_record)

{'nome': 'Roberto', 'idade': 20}


Lista de dicionários:

In [44]:
records = [{'nome':'Alfredo', 'idade': 23},
           {'nome':'Fernanda', 'idade': 16},
           {'nome':'Carla', 'idade':33}]

In [61]:
# acesse o nome da Fernanda: complete e descomente a linha a seguir
print(records[1]['nome'])

Fernanda


In [75]:
# crie uma lista com todos os nomes da lista records.
# resultado deve ser uma lista ['Alfredo', 'Fernanda', 'Carla']
# 1. Utilizando a forma tradicional de criar lista com append
nlist = []
for v in records:
    nlist.append(v['nome'])
print(nlist)

['Alfredo', 'Fernanda', 'Carla']


In [78]:
# 2. Utilizando a forma de list comprehension
nlist2 = [v['nome'] for v in records]
print(nlist2)

['Alfredo', 'Fernanda', 'Carla']


# Exercícios usando NumPy

Os seguintes exercícios devem usar apenas o pacote NumPy.
Não se deve utilizar nenhum outro pacote adicional.

Existem vários exemplos de uso de NumPy no conjunto de
notebooks tutorias disponíveis no GitHub:
- https://github.com/robertoalotufo/ia898/blob/master/master/0_index.ipynb

In [79]:
import numpy as np

In [80]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
A = np.arange(24).reshape(4,6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


### rows, cols, dimensions, shape and datatype

In [87]:
# imprima o número de linhas de A
print(A.shape[0])
# imprima o número de colunas de A
print(A.shape[1])
# imprima o número de dimensões de A
print(len(A.shape))
# imprima o shape de A:
print(A.shape)
# imprima o tipo de dados (dtype) dos elementos de A:
print(A.dtype)

4
6
2
(4, 6)
int64


### Reshape

In [88]:
# Seja o vetor unidimension a:
a = np.array([1,2,3,4])
print(a, a.shape)

[1 2 3 4] (4,)


In [91]:
# converta o vetor unidimensional a em uma matriz vetor coluna (4 linhas e 1 coluna) utilizando reshape
a = a.reshape(4,1)
print(a)

[[1]
 [2]
 [3]
 [4]]


## Operações aritméticas

In [92]:
B = A + 10
B

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

### Array binário (booleano)

In [99]:
# crie uma matriz booleana C com True nos elementos de B menores que 18 (não utilize loop explícito)
C = B < 18 # modify your code here
print(C)

[[ True  True  True  True  True  True]
 [ True  True False False False False]
 [False False False False False False]
 [False False False False False False]]


## Indexação booleana

Veja um programa que cria matriz D_loop a partir da matriz B, porém trocando os elementos menores que 18 por seus valores negativos

In [27]:
D_loop = B.copy()
for row in np.arange(B.shape[0]):
    for col in np.arange(B.shape[1]):
        if B[row,col] < 18:
            D_loop[row,col] = - B[row,col]
print(D_loop)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


### Troque o programa acima por uma única linha sem loop

In [128]:
D = np.where(B < 18, -B, B)  # << modifique aqui utilizando indexação booleana
print(D)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


## Redução de eixo: soma

Operações matriciais de redução de eixo são muito úteis e importantes.
É um conceito importante da programação matricial.

Estude o exemplo a seguir:

In [129]:
print(A)
print('-'*30)
print(A.shape)
print('-'*30)
As = A.sum(axis=0)
print(As)
print('-'*30)
print(As.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
------------------------------
(4, 6)
------------------------------
[36 40 44 48 52 56]
------------------------------
(6,)


In [133]:
# imprima o número de dimensões do array  As = A.sum(axis=0)?
print(len(As.shape))
# calcule o valor médio do array A
print(A.mean())


1
11.5


$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max}} - A_{min} $$

In [135]:
# Criar a matriz C que é a normalização de A, de modo que os valores de C estejam entre 0 e 1
C = ((A-np.min(A))/(np.max(A)))-(np.min(A))
print(C)

[[ 0.          0.04347826  0.08695652  0.13043478  0.17391304  0.2173913 ]
 [ 0.26086957  0.30434783  0.34782609  0.39130435  0.43478261  0.47826087]
 [ 0.52173913  0.56521739  0.60869565  0.65217391  0.69565217  0.73913043]
 [ 0.7826087   0.82608696  0.86956522  0.91304348  0.95652174  1.        ]]


In [136]:
# Modificar o exercício anterior, porém agora faça a normalização para cada coluna de A
# de modo que as colunas da matriz D estejam entre os valores de 0 a 1.
# Dica: utilize o conceito de redução de eixo
D = 1 - (np.max(A,axis=0) - A)/(np.max(A,axis=0) - np.min(A,axis=0) )
print(D)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]
 [ 0.66666667  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667]
 [ 1.          1.          1.          1.          1.          1.        ]]


## Fatiamento em arrays (slicing)

In [137]:
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [138]:
# esta indexação é chamada fatiamento:
AA = A[:,1::2]
print(AA)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


In [139]:
# criar a matriz AB apenas com as linhas pares da matriz A, utilizando o conceito de fatiamento:
AB = A[0::2,::]
print(AB)

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]


In [140]:
# crie a matriz AC com mesmo shape da matriz A, porém com os elementos na ordem inversa:
# trocando a ordem das linhas e das colunas
AC = A[::-1,::-1]
print(AC)

[[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


## Produto matricial  (dot product)

Calcule a matriz E dada pelo produto matricial entre a matriz A e sua transposta: 
$$ E = A A^T $$

In [141]:
E = A.dot(A.T) # modify your code here
print(E)

[[  55  145  235  325]
 [ 145  451  757 1063]
 [ 235  757 1279 1801]
 [ 325 1063 1801 2539]]


In [144]:
print(A.shape)
print(A.T.shape)

(4, 6)
(6, 4)


In [143]:
# Descomente a linha e explique
# por que a operação de multiplicação dá erro?
Ee = A * A.T

ValueError: operands could not be broadcast together with shapes (4,6) (6,4) 

In [146]:
print(A.shape)
print(A.T.shape)

(4, 6)
(6, 4)


O broadcast no numpy tem duas regras:

    a) Funciona quando as duas dimensões são iguais;
    
    b) Quando uma delas é 1;
    

Como A.shape[0] != 1 && AT.shape[0] !=1 && A.shape[0] ! = A.T.shape[0], então a operação dá erro.

## Matrizes multidimensionais

Em deep learning, iremos utilizar matrizes multidimensionais
que são denominados como arrays no NumPy. Tensorflow usa o nome de tensor para
suas matrizes multimensionais.

Matrizes de dimensões maior que 4 são de difícil intuição. A melhor forma de lidar
com elas é observando o seu *shape*.

### 3-D array

In [148]:
F = A.reshape(2,3,4)
print(F)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Indexação


Estude e explique as seguintes indexações:

In [151]:
#Essa matriz é segunda matriz (da dimensão 0) de 3x4 elementos, do tensor F
print(F[1])


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [153]:
#Essa matriz é a PRIMEIRA LINHA da segunda matriz (da dimensão 0) de 3x4 elementos, do tensor F
print(F[1,0])

[12 13 14 15]


In [155]:
#Essa matriz é ao TERCEIRO ELEMENTO DA primeira linha da segunda matriz (da dimensão 0) de 3x4 elementos, do tensor F

print(F[1,0,2])

14


In [157]:
# imprima o número de dimensões de F
print(len(F.shape))
# imprima o shape de F
print(F.shape)

3
(2, 3, 4)


## Redução de eixo - aplicado a dois eixos simultâneos

In [169]:
# calcule o valor médio das matrizes F[0] e F[1], com apenas um comando usando F.mean(??)
print(np.mean( np.array([F[0,:,:], F[1,:,:] ]), axis=0 ))
print(np.mean( np.array([F[0,:,:], F[1,:,:] ]) ))


[[  6.   7.   8.   9.]
 [ 10.  11.  12.  13.]
 [ 14.  15.  16.  17.]]
11.5


## Broadcasting

O que significa o conceito de broadcasting em NumPy?

In [179]:
# Usando o conceito de broadcast, mude o shape do vetor a para que o broadcast possa ocorrer em G = A + a
a = np.arange(4)
#print(a.shape)
a = a.reshape(4,1)
#print(A.shape)
G = A + a
print(G)

[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]


## Function - split - dados treino e validação

Defina uma função que receba como entrada um array unidimensional e gere como saída o
array na codificação one-hot, conforme exemplo a seguir:

In [170]:
# Entrada, vetor de 5 elementos representando classes
aa = np.arange(90).reshape(10,9)
print(aa)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [171]:
# Saída da função t.v = split(aa, 0.8)
t = np.arange(72).reshape(8,9)
print(t)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


In [172]:
v = np.arange(72,90).reshape(2,9)
print(v)

[[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [201]:
print(aa.shape)

(10, 9)


In [208]:
print(aa.shape)
bb = aa[:int(aa.shape[0]*0.8)]
print(bb.shape)

(10, 9)
(8, 9)


In [245]:
# Evite o uso de laço explícito
# Não utilize outras bibliotecas além do NumPy
def split(dados, split_factor):
    '''
    divide a matriz dados em dois conjuntos:
    matriz train: split_factor * n. de linhas de dados
    matriz val: 1-split_factor * n. de linhas de dados
    parametros entrada:
    dados: matriz de entrada
    split: entre 0. e 1. - fator de divisão em duas matrizes
    parametros de saída:
    train : matriz com as linhas iniciais de dados
    val: matriz com as linhas restantes
    '''
    assert split_factor > 0 and split_factor < 1 
    # insert your code here
    train = dados[:int(dados.shape[0]*split_factor)]
    val = dados[int(dados.shape[0]*split_factor):]                       
    return train, val

t,v = split(aa, 0.8)
#print('-'*30)
print('v=\n', v)
#print('-'*30)

print('t=\n', t)

v=
 [[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]
t=
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


In [246]:
# Teste sua função com outros valores
teste = np.random.rand(10,10)

teste_2 = teste_2.reshape(50,2)
t,v = split(teste_2, 0.50)
#print('-'*30)
print('v=\n', v.shape)
#print('-'*30)

print('t=\n', t.shape)

v=
 (25, 2)
t=
 (25, 2)


# Programação Orientada a Objetos

Documentação oficial: https://docs.python.org/3/tutorial/classes.html

Forma clássica de definição de uma função:

In [247]:
data = np.array([13, 63, 5, 378, 58, 40])

def avg(d):
    return sum(d)/len(d)
    
avg(data)

92.833333333333329

## Definição da classe, variáveis, inicialização e método

Definição da classe `MyAvg`, contendo duas variávels: `id` (compartilhada) e `d`; inicialização e método `avg`.

In [181]:
class MyAvg:
    id = 0.33                # variável compartilhada com todas as instâncias
    
    def __init__(self,data):
        self.d = data        # variável associada a cada instância 
        
    def avg(self): # método para calcular a média
        return sum(self.d)/len(self.d)

Objetos `a` e `b` são instâncias da classe `myavg`.
Instanciar uma classe é inicializá-la através da chamada ao método __init__:

In [182]:
a = MyAvg(data)
b = MyAvg(2*data)

Aplicação do método `avg()`, retorna a média dos dados dos objetos a e b:

In [183]:
print(a.avg())
print(b.avg())

92.8333333333
185.666666667


In [187]:
# Imprima os valores dos dados associados aos objetos a e b:
print(a.d)
print(b.d)

[ 13  63   5 378  58  40]
[ 26 126  10 756 116  80]


In [186]:
# Imprima a variável compartilhada `id` de cada objeto a e b:
print(a.id)
print(b.id)

0.33
0.33


## Herança de classe

In [189]:
class MyAvgStd(MyAvg):
    def var(self): # método adicional para calcular a variância
        u = self.avg()
        return np.sqrt(np.sum((self.d - u)**2)/len(self.d))

In [190]:
c = MyAvgStd(data)

In [191]:
print('media:',c.avg())
print('variancia:',c.var())

media: 92.8333333333
variancia: 129.29477518


In [193]:
# imprima os dados associados ao objeto c e a sua variável compartilhada id
print(c.d)
print(c.id)

[ 13  63   5 378  58  40]
0.33


### Exercício: convertendo a função `split` na classe `C_Split`

Implemente a classe `C_Split` para ter a mesma funcionalidade da função `split` feita acima

In [248]:
class C_Split():
    def __init__(self,matrix):
        self.d = matrix
        #self.split_factor
    def split(self, split_factor ):
        train = self.d[:int(self.d.shape[0]*split_factor)]
        val = self.d[int(self.d.shape[0]*split_factor):]    
        return train,val
        

In [249]:
data_train_val = C_Split(aa)
train, val = data_train_val.split(0.8)
print('train=\n', train)
print('val=\n', val)

train=
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
val=
 [[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


## Classe com métodos `__len__` e `__getitem__`

Uma classe com métodos `__len__` e `__getitem__` permite que os objetos possam ser indexados e calculado o seu número de elementos.

Veja o exemplo a seguir:

In [236]:
class Word():
    def __init__(self, phrase):
        self.wordlist = phrase.split() # separa frase em uma lista de palavras
    
    def __len__(self):
        return len(self.wordlist)
    
    def __getitem__(self,x):
        return self.wordlist[x]

In [241]:
frase = 'Esta frase é formada por 7 palavras'
palavras = Word(frase)
print(list(palavras))

['Esta', 'frase', 'é', 'formada', 'por', '7', 'palavras']


In [238]:
palavras[3]  # permite a indexação do objeto

'formada'

In [63]:
print(len(palavras))

7


### Exercício para indexar elementos de um dicionário

Um dicionário em Python não é indexado. Por exemplo seja o dicionário `d` a seguir.
Não é possível indexar d[0] ou d[1] para buscar o primeiro ou segundo par (chave:valor).

In [243]:
d = {'a':1,'b': 2}

Implementar uma classe que receba um dicionário e permita que ele possa ser indexado.
Para converter um dicionário em uma lista de pares, use:

In [244]:
list(d.items())

[('a', 1), ('b', 2)]

Complete a definição da classe `dicdata` a seguir para que um dicionário possa ser
indexado:

In [272]:
print(len(d))
lista_items = d.items()
print(list(lista_items)[1])

2
('b', 2)


In [275]:
class DicData():
    def __init__(self, dic):
        self.dictlist = dic.items()

    def __len__(self):
        return(len(self.dictlist))
    def __getitem__(self,x):
        return list(self.dictlist)[x]


In [276]:
dd = DicData(d)
print(len(dd))
print(dd[0])

2
('a', 1)


## Iteradores

Iteradores são uteis para serem usados em estruturas do tipo `for a in b:`.

Listas em Python são consideradas iteráveis, pois podem ser utilizadas nessa estrutura:

In [277]:
for i in ['a', 'b', 'c']:
    print(i)

a
b
c


O método do `range()` do python também é um iterável:

In [278]:
for i in range(3):
    print(i)

0
1
2


É possível acessar o iterador destas estruturas utilizando o método `iter()` do Python e então é possível percorrer seus elementos utilizado `next()`:

In [280]:
lista = ['a', 'b', 'c']
iterador = iter(lista)
print('tipo de iterador:', type(lista))
print('tipo de iterador:', type(iterador))
print(next(iterador))

tipo de iterador: <class 'list'>
tipo de iterador: <class 'list_iterator'>
a


O acesso de iteradores é sequencial e após o ultimo elemento uma exceção é levantada indicando o fim do iterador.
Descomente o último `next` e veja o tipo da exceção que acontece.

In [281]:
print(next(iterador))
print(next(iterador))
print(next(iterador))

b
c


StopIteration: 

## Criando objetos iteráveis

Para implementar um objeto iterador é preciso escrever um método `__next__()` para a classe e para que ele seja acessível como iterável também é necessário escrever um método `__iter__()`: 

In [283]:
class WordIterator():
    def __init__(self, phrase):
        self.words = phrase.split()
        
    def __iter__(self):
        self.iter_index = 0
        return self
    
    def __next__(self):
        if self.iter_index < len(self.words):
            i = self.iter_index
            self.iter_index += 1
            return self.words[i]
        else:
            raise StopIteration()

A classe acima é um iterador e é iterável. 

No método `__iter__()` reiniciamos o índice inicial para o iterador e retornamos o próprio objeto (um iterador).

No método `__next__()` retornamos a palavra do índice atual ou a exceção de parada, caso seja o fim.

In [284]:
frase = 'Esta frase é formada por 7 palavras'
iterador_de_palavras = WordIterator(frase)

In [285]:
for palavra in iterador_de_palavras:
    print(palavra)

Esta
frase
é
formada
por
7
palavras


### Exercício com iterador

Crie uma classe `DictIterator` que permita varrer os itens de um dicionário utilizando o `for`

In [ ]:
class DicData():
    def __init__(self, dic):
        self.dictlist = dic.items()

    def __len__(self):
        return(len(self.dictlist))
    def __getitem__(self,x):
        return list(self.dictlist)[x]

In [289]:
class DictIterator():
    def __init__(self, dic):
        self.dictlist = dic.items()

    def __len__(self):
        return(len(self.dictlist))
    def __getitem__(self,x):
        return list(self.dictlist)[x]
    def __iter__(self):
        self.iter_index = 0
        return self

    def __next__(self):
        if self.iter_index < len(list(self.dictlist)):
            i = self.iter_index
            self.iter_index += 1
            return list(self.dictlist)[i]
        else:
            #print("The generator has come to an end!")
            raise StopIteration()

In [290]:
d = {'a':1,'b': 2, 'c': 3}
d_iter = DictIterator(d)
for i in d_iter:
    print(i)

('a', 1)
('b', 2)
('c', 3)


## Objeto como função

É possível declarar uma classe contendo um objeto possa ser chamado (*callable object*).
Para isso, a classe deve conter o método `__call__`. Veja o exemplo a seguir:

In [291]:
class Scale():
    def __init__(self, w):
        self._w = w
    def __call__(self, x):
        return x * self._w

In [292]:
s = Scale(100.)
print(s(5))


500.0


### Exercício de classe contendo objeto chamável

Defina uma classe herdada da classe `Scale` que permita modificar a variável `self._w`.

In [297]:
class AjustaPeso(Scale):
    def wset(self,new_value):
        self._w = new_value
        return self._w


In [298]:
ap = AjustaPeso(100.)
print(ap(5))

500.0


In [300]:
ap.wset(10)
print(ap(5))

50


# Fim do notebook